name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install fonts
      run: |
        sudo apt-get update
        sudo apt-get install -y fontconfig
        sudo apt-get install -y fonts-liberation 
        sudo fc-cache -f -v
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 7.0.x

    - name: Restore dependencies
      run: dotnet restore UnitTest/UnitTest.csproj

    - name: Build
      run: dotnet build UnitTest/UnitTest.csproj --no-restore
      
    - name: Test
      run: dotnet test UnitTest/UnitTest.csproj --no-build --verbosity normal
